version: '3'

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USR}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PWD}
    ports:
      - ${DB_PORT}:27017
